import re
from pathlib import Path, PurePosixPath

from .constants import (
    IMPORT_END_PREFIX,
    IMPORT_START_PREFIX,
    RUNTIME_VERSION,
    STATE_END,
    STATE_START,
    TEMPLATE_VERSION,
)
from .schema import pretty_json, read_text_preserve, sha256_file


IMPORT_BLOCK_RE = re.compile(
    r"<!-- workflow-imported-rules:start:(?P<name>[^>]+) -->\n"
    r"(?P<body>.*?)"
    r"<!-- workflow-imported-rules:end:(?P=name) -->",
    re.DOTALL,
)


def read_template(assets_root, relative):
    return read_text_preserve(Path(assets_root) / relative)


def render_template(assets_root, relative, replacements):
    text = read_template(assets_root, relative)
    for key, value in replacements.items():
        text = text.replace("{{" + key + "}}", value)
    return text


def imported_section(source_name, content):
    if content is None or content == "":
        return ""
    ending = "" if content.endswith(("\n", "\r")) else "\n"
    return (
        "\n## Imported Existing Rules\n\n"
        f"Source: `{source_name}`\n\n"
        f"{IMPORT_START_PREFIX}{source_name} -->\n"
        f"{content}{ending}"
        f"{IMPORT_END_PREFIX}{source_name} -->\n"
    )


def extract_imported_sections(text):
    if not text:
        return {}
    return {match.group("name"): match.group("body") for match in IMPORT_BLOCK_RE.finditer(text)}


def render_state(mode, workspace_id=None):
    state = {
        "schema_version": 1,
        "runtime_version": RUNTIME_VERSION,
        "template_version": TEMPLATE_VERSION,
        "mode": mode,
        "status": "initialized",
        "revision": 0,
        "workspace_id": workspace_id,
        "active_task_id": None,
        "tasks": {},
        "completed_tasks": {},
        "recent_events": [],
    }
    return "# Workflow State\n\n" + STATE_START + "\n" + pretty_json(state) + STATE_END + "\n"


def render_config(mode, managed_files, template_baselines=None, runtime_manifest_sha256=None):
    config = {
        "schema_version": 1,
        "runtime_version": RUNTIME_VERSION,
        "template_version": TEMPLATE_VERSION,
        "mode": mode,
        "managed_files": sorted(managed_files),
        "runtime_manifest_sha256": runtime_manifest_sha256,
        "template_baselines": dict(sorted((template_baselines or {}).items())),
        "routing_policy": {
            "plan": {"role": "pm", "model": "gpt-5.6-sol", "effort_chain": ["ultra", "max", "xhigh", "high"]},
            "plan-review": {"role": "plan-reviewer", "model": "gpt-5.6-sol", "effort_chain": ["ultra", "max", "xhigh", "high"]},
            "code": {"role": "builder", "model": "gpt-5.6-terra", "effort_chain": ["xhigh", "high", "medium"]},
            "text": {"role": "writer", "model": "gpt-5.6-luna", "effort_chain": ["xhigh", "high", "medium"]},
            "reporter": {"role": "reporter", "model": "gpt-5.6-luna", "effort_chain": ["xhigh", "high", "medium"]},
            "explore": {"role": "explorer", "model": "gpt-5.6-luna", "effort_chain": ["high", "medium"]},
            "test": {"role": "tester", "model": "gpt-5.6-terra", "effort_chain": ["xhigh", "high"]},
            "code-review": {"role": "code-reviewer", "model": "gpt-5.6-terra", "effort_chain": ["xhigh", "high"]},
            "risk": {"role": "risk-reviewer", "model": "gpt-5.6-sol", "effort_chain": ["ultra", "max", "xhigh", "high"]},
            "other": {"role": "explorer", "model": "gpt-5.6-terra", "effort_chain": ["high", "medium"]},
        },
        "concurrency": {"max_readers": 3, "max_writers": 1},
        "assurance_levels": {"L1": "light", "L2": "conditional-gates", "L3": "batch-and-evidence", "L4": "confirmation-rollback-monitoring"},
    }
    return pretty_json(config)


def render_project(scan, mode):
    lines = [
        "# Project Facts", "", "Generated by initialize-project-workflow from local files.", "",
        f"- Mode: {mode}", f"- Git repository: {'yes' if scan['is_git'] else 'no'}",
        "- Acceptance coverage: \u672a\u53d1\u73b0/\u672a\u9a8c\u8bc1", "",
        "## Discovered Commands", "",
    ]
    if scan.get("commands"):
        for name, value in scan["commands"].items():
            if isinstance(value, dict) and value.get("command"):
                lines.append(f"- `{name}`: `{value['command']}` (evidence: `{value.get('evidence', '未发现/未验证')}`)")
            else:
                evidence = value.get("evidence", "未发现/未验证") if isinstance(value, dict) else value
                lines.append(f"- `{name}`: 未发现/未验证 (evidence: `{evidence}`)")
    else:
        lines.append("- \u672a\u53d1\u73b0/\u672a\u9a8c\u8bc1")
    lines.extend(["", "- Sensitive-file patterns: `*.env`, `*.pem`, `*.key`, `*token*`, `*secret*`", "", "## Deterministic File Scan", ""])
    for category in ("manifests", "readmes", "source", "tests", "scripts"):
        files = scan["files"][category]
        lines.append(f"### {category.title()}")
        if files:
            for rel in files:
                digest = scan["file_hashes"][rel][:12]
                lines.append(f"- `{rel}` sha256:{digest}")
        else:
            lines.append("- (none)")
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def template_hashes(assets_root):
    root = Path(assets_root)
    hashes = {}
    if not root.exists():
        return hashes
    for path in sorted(root.rglob("*"), key=lambda item: item.relative_to(root).as_posix().lower()):
        if path.is_file():
            rel = path.relative_to(root).as_posix()
            if ".." in PurePosixPath(rel).parts:
                raise ValueError(f"template path escapes root: {rel}")
            hashes[rel] = sha256_file(path)
    return hashes
